name: Scheduled fetch

on:
  schedule:
    - cron: '15 * * * *' # 毎事15分に実行
    #- cron: '8 7 * * *' # 毎日16:08分に実行 (JST=UTC+9)

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: fetch
        run: |
          deno run -A downloadLatest.js
          deno run -A makeData.js
      - name: commit and push
        run: |
          git config --global user.email "workflow@example.com"
          git config --global user.name "workflow user"
          git add .
          git commit -m 'update data' && git push ${REPO} HEAD:${{github.event.pull_request.head.ref}} || true
          git push
